failed to update to 3.10
ravis-MacBook-Pro:binarytest rgupta$ oc tag docker-registry.default.svc:5000/dev/welcome-php@sha256:f866bc0ee7113fc6b0624797be1d5f69bf021a71e52ee93ca79eb9c729a02db5/dev/welcome-php:promote-qa
error: invalid SOURCE: invalid reference format