failed to update to 3.10
Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not receiving updates. You can use subscription-manager on the host to register and assign subscriptions.


Error getting repository data for rhel-7-server-rpms, repository not found
Removing intermediate container 6ca609cc4ea0
error: build error: The command '/bin/sh -c yum install nmap-ncat --disablerepo=* --enablerepo=rhel-7-server-rpms -y && yum clean all -y' returned a non-zero code: 1